// Copyright (C) 2025-2026 TESOBE GmbH
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
syntax = "proto3";

package code.obp.grpc.logcache.g1;

import "google/protobuf/timestamp.proto";

service LogCacheStreamService {
  rpc StreamLogCacheEntries (StreamLogCacheRequest) returns (stream LogCacheEntry);
}

message StreamLogCacheRequest {
  LogLevel level = 1;
}

message LogCacheEntry {
  LogLevel level = 1;
  string message = 2;
  google.protobuf.Timestamp timestamp = 3;
  string api_instance_id = 4;
}

enum LogLevel {
  LOG_LEVEL_UNSPECIFIED = 0;
  TRACE = 1;
  DEBUG = 2;
  INFO = 3;
  WARNING = 4;
  ERROR = 5;
  ALL = 6;
}
