// Copyright (C) 2025-2026 TESOBE GmbH
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
syntax = "proto3";

package code.obp.grpc.metricsstream.g1;

service MetricsStreamService {
  rpc StreamMetrics (StreamMetricsRequest) returns (stream MetricEvent);
}

message StreamMetricsRequest {
  string consumer_id = 1;
  string user_id = 2;
  string verb = 3;
  string url_substring = 4;
  string implemented_by_partial_function = 5;
  string app_name = 6;
  string consent_reference_id = 7;
}

message MetricEvent {
  string url = 1;
  string date = 2;
  int64 duration = 3;
  string user_id = 4;
  string username = 5;
  string app_name = 6;
  string developer_email = 7;
  string consumer_id = 8;
  string implemented_by_partial_function = 9;
  string implemented_in_version = 10;
  string verb = 11;
  int32 status_code = 12;
  string correlation_id = 13;
  string source_ip = 14;
  string target_ip = 15;
  string api_instance_id = 16;
  string operation_id = 17;
  string consent_reference_id = 18;
}
